export const factions = {
  neutral: "neutral",
  bandit: "bandit",
  mercenaries: "mercenary",
  mercenary: "mercenary",
  military: "military",
  militaries: "military",
  corps: "corpus",
  coprs: "corpus",
  corpus: "corpus",
  scientific: "scientist",
  sci: "scientist",
  scientists: "scientist",
  scientist: "scientist",
  svoboda: "freedom",
  freedom: "freedom",
  dolg: "duty",
  duty: "duty",
  noon: "monolith",
  monolith: "monolith",
  granit: "monolith",
  varta: "varta",
  spark: "spark",
};
