import { describe, expect, it } from "vitest";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { parseUasset } from "./uasset.mts";
import { writeModLocalization, writeModLocalizationDatabase } from "./text.mts";

/** A mod folder as `writeModLocalization` expects to find one: `raw/Stalker2/Content` under it. */
const scratchMod = (name: string) => {
  const modDir = path.join(mkdtempSync(path.join(tmpdir(), "s2-mod-")), name);
  mkdirSync(path.join(modDir, "raw/Stalker2/Content"), { recursive: true });
  // The module URL is what the function resolves the mod from, not the cwd.
  return { modDir, moduleUrl: pathToFileURL(path.join(modDir, "writeLocalization.mts")).href };
};

const entries = [
  { SID: "sid_items_Thing_name", LanguagesToLocalizedStrings: { English: "Thing" } },
];

describe("writeModLocalization", () => {
  it("creates a mod's first localization asset without the Mod Editor", () => {
    const { modDir, moduleUrl } = scratchMod("BrandNewMod");
    writeModLocalization(moduleUrl, entries);

    const asset = path.join(modDir, "raw/Stalker2/Content/BrandNewMod-localization.uasset");
    const parsed = parseUasset(asset);
    // The package is named after where it lives, so the cooker addresses it under this mod.
    expect(parsed.summary.packageName).toBe("/BrandNewMod/BrandNewMod-localization");
    expect(parsed.exports[0].properties).toEqual({ LocalizedTexts: entries });
    expect(readFileSync(asset).includes("FactionPatches")).toBe(false);
  });

  it("honours the asset name a mod shipping several assets asks for", () => {
    const { modDir, moduleUrl } = scratchMod("MultiAssetMod");
    writeModLocalization(moduleUrl, entries, "MultiAssetMod-Localization3");

    const asset = path.join(modDir, "raw/Stalker2/Content/MultiAssetMod-Localization3.uasset");
    expect(parseUasset(asset).summary.packageName).toBe(
      "/MultiAssetMod/MultiAssetMod-Localization3",
    );
  });

  it("rewrites an asset it already created without renaming it again", () => {
    const { modDir, moduleUrl } = scratchMod("SecondRunMod");
    writeModLocalization(moduleUrl, entries);
    const asset = path.join(modDir, "raw/Stalker2/Content/SecondRunMod-localization.uasset");
    const first = readFileSync(asset);

    writeModLocalization(moduleUrl, entries);

    // Same entries, same bytes: the committed artifact does not churn on every prepare run.
    expect(readFileSync(asset)).toEqual(first);
  });

  it("does not write into a mod with no SDK folder", () => {
    const { modDir, moduleUrl } = scratchMod("NoSdkMod");
    writeModLocalization(moduleUrl, entries);

    expect(existsSync(path.join(modDir, "sdk"))).toBe(false);
  });
});

/** The `Autogenerated_<n>_LocalizationDatabase.uasset` a mod folder ends up holding. */
const databaseAsset = (modDir: string) => {
  const dir = path.join(modDir, "raw/Stalker2/Content");
  const file = readdirSync(dir).find((f) => f.includes("LocalizationDatabase"));
  if (!file) throw new Error(`no localization database in ${dir}`);
  return path.join(dir, file);
};

describe("writeModLocalizationDatabase", () => {
  it("generates the database the game reads alongside the text asset", () => {
    const { modDir, moduleUrl } = scratchMod("DatabaseMod");
    writeModLocalization(moduleUrl, entries);

    const asset = databaseAsset(modDir);
    const parsed = parseUasset(asset);
    expect(parsed.summary.packageName).toBe(`/DatabaseMod/${path.basename(asset, ".uasset")}`);
    expect(parsed.exports.at(-1)?.className).toBe("ModLocalizationDatabaseDataAsset");
    expect(parsed.exports.at(-1)?.properties?.LocalizationDatabase).toEqual({
      sid_items_Thing_name: { LanguagesToLocalizedStrings: { English: "Thing" } },
    });
    expect(readFileSync(asset).includes("DecoupledRanks")).toBe(false);
  });

  it("puts Ukrainian first, the way the editor's gather does", () => {
    const { modDir, moduleUrl } = scratchMod("OrderMod");
    writeModLocalization(moduleUrl, [
      {
        SID: "sid_items_Thing_name",
        LanguagesToLocalizedStrings: {
          "ELocalizationLanguage::English": "Thing",
          "ELocalizationLanguage::Ukrainian": "\u0420\u0456\u0447",
        },
      },
    ]);

    const database = parseUasset(databaseAsset(modDir)).exports.at(-1)?.properties
      ?.LocalizationDatabase as Record<string, { LanguagesToLocalizedStrings: object }>;
    expect(Object.keys(database.sid_items_Thing_name.LanguagesToLocalizedStrings)).toEqual([
      "ELocalizationLanguage::Ukrainian",
      "ELocalizationLanguage::English",
    ]);
  });

  it("gathers every text asset the mod ships into one database", () => {
    const { modDir, moduleUrl } = scratchMod("TwoAssetMod");
    writeModLocalization(moduleUrl, entries, "TwoAssetMod-Localization1");
    writeModLocalization(
      moduleUrl,
      [{ SID: "sid_items_Other_name", LanguagesToLocalizedStrings: { English: "Other" } }],
      "TwoAssetMod-Localization2",
    );

    // The second write gathers off disk, so it picks up the first asset too rather than replacing
    // its entries - which is what the editor does when a mod holds several text assets.
    const database = parseUasset(databaseAsset(modDir)).exports.at(-1)?.properties
      ?.LocalizationDatabase as Record<string, unknown>;
    expect(Object.keys(database)).toEqual(["sid_items_Thing_name", "sid_items_Other_name"]);
  });

  it("keeps the database's name and bytes stable across runs", () => {
    const { modDir, moduleUrl } = scratchMod("StableMod");
    writeModLocalization(moduleUrl, entries);
    const asset = databaseAsset(modDir);
    const first = readFileSync(asset);

    writeModLocalizationDatabase(moduleUrl);

    expect(databaseAsset(modDir)).toBe(asset);
    expect(readFileSync(asset)).toEqual(first);
  });
});
