import path from "node:path";
import { existsSync, readdirSync, statSync } from "node:fs";

import { logger } from "./logger.mts";
import { hasBaseGamePackage } from "./asset-registry.mts";
import { allValidMods, modsFolder } from "./mod-context.mts";

/**
 * How often can `cookMod`'s `overrideOnly` shortcut fire, and what blocks it?
 *
 * A full cook boots the Mod Editor commandlet twice (GSCCookModOverrideContent, then
 * GSCCookModNewContent) at ~21 min of startup each, so skipping the NewContent pass halves
 * the wall clock. `cook.mts` skips it only when the PackageClassifier yields zero new
 * packages; this script reports, for every mod in Mods/, whether that already holds, whether
 * it would hold under a wider rule, or whether the pass is genuinely load-bearing.
 *
 * Read-only: it touches no SDK state and runs no cook.
 */

/** Only Unreal packages are classified; .cfg patches are loose staged files. */
const packageExtensions = new Set([".uasset", ".umap"]);

/**
 * The mod's own `Content/<Mod>.uasset` is a GameFeatureData that registers
 * `Content/GameLite/ModGameData/<Mod>/` as a config path and carries the world-partition
 * content-bundle GUID. It has no `/Game/` counterpart, so it always classifies as new content
 * and single-handedly forces the NewContent pass - even for a mod that ships neither a
 * ModGameData tree nor world-partition content, where it has nothing to register.
 *
 * Matched by position rather than by name: it sits directly in Content/ and is usually named
 * after the mod, but a mod carrying `sdkModNameOverride`, or one repacked from someone else's
 * plugin, ships it under that other name (NoThreatMarkers ships `PAK_Mod.uasset`).
 * Autogenerated_* assets also sit at that depth and are excluded separately.
 */
const isModRoot = (tail: string) => !tail.includes("/");

/**
 * Only the NewContent pass stages `GameLite/ModGameData`
 * (`Config/Custom/ModCookNewContent/DefaultGame.ini`: `+DirectoriesToAlwaysStageAsUFS_DLC`).
 * A mod that ships no such tree gets nothing out of that half of the pass.
 */
const modGameDataDir = (contentDir: string) => path.join(contentDir, "GameLite", "ModGameData");

/**
 * World-partition content: cooked into the mod's container by the NewContent pass, which is
 * also the only pass that keeps WorldMap_WP in MapsToCook. A mod shipping any of this needs
 * the pass whatever else is true.
 */
const isWorldPartitionPackage = (tail: string) =>
  /(^|\/)(__ExternalActors__|__ContentBundle__|ContentBundle)(\/|$)/i.test(tail);

/**
 * `Autogenerated_*_WorldSubsystemData|LocalizationDatabase|ActorReplacementData` end up in
 * neither classifier list, which means *both* passes cook them - so the OverrideContent
 * container already carries them and skipping NewContent does not drop them.
 * `ActorPatchesData|ActorDeletionsData` are override content. Mirrors package-classifier.mts.
 */
const autogenerated = /^Autogenerated_\d+_([A-Za-z]+)$/;
const autogeneratedNotNew = new Set([
  "WorldSubsystemData",
  "LocalizationDatabase",
  "ActorReplacementData",
  "ActorPatchesData",
  "ActorDeletionsData",
]);

function walk(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((entry) => {
    const full = path.join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

type Verdict = "can-skip-now" | "could-skip-if-root-asset-inert" | "needs-both";

type ModReport = {
  mod: string;
  verdict: Verdict;
  packages: number;
  newPackages: string[];
  hasModGameData: boolean;
  reason: string;
};

function analyzeMod(mod: string): ModReport {
  // The authoritative Content tree is the repo's raw/ one; push-to-sdk copies it into
  // Stalker2/Mods/<Mod>/Content, which is what the classifier later walks.
  const contentDir = path.join(modsFolder, mod, "raw", "Stalker2", "Content");
  const tails = walk(contentDir)
    .filter((f) => packageExtensions.has(path.extname(f).toLowerCase()))
    .map((f) =>
      path
        .relative(contentDir, f)
        .replaceAll(path.sep, "/")
        .replace(/\.[^.]+$/, ""),
    )
    .sort();

  const hasModGameData = existsSync(modGameDataDir(contentDir));
  const newPackages = tails.filter((tail) => {
    const kind = autogenerated.exec(tail)?.[1];
    if (kind && autogeneratedNotNew.has(kind)) return false;
    // hasBaseGamePackage returns null when the registry is unreadable; treat that as new so
    // the report errs towards "needs the pass" rather than silently promising a shortcut.
    return hasBaseGamePackage(tail) !== true;
  });

  const wp = newPackages.filter(isWorldPartitionPackage);
  const beyondRoot = newPackages.filter((t) => !isModRoot(t) && !isWorldPartitionPackage(t));

  if (wp.length) {
    return {
      mod,
      verdict: "needs-both",
      packages: tails.length,
      newPackages,
      hasModGameData,
      reason: `${wp.length} world-partition package(s) only the NewContent pass cooks`,
    };
  }
  if (beyondRoot.length) {
    return {
      mod,
      verdict: "needs-both",
      packages: tails.length,
      newPackages,
      hasModGameData,
      reason: `${beyondRoot.length} genuinely new package(s), e.g. ${beyondRoot[0]}`,
    };
  }
  if (hasModGameData) {
    return {
      mod,
      verdict: "needs-both",
      packages: tails.length,
      newPackages,
      hasModGameData,
      reason: "ships GameLite/ModGameData, which only the NewContent pass stages",
    };
  }
  if (newPackages.length) {
    return {
      mod,
      verdict: "could-skip-if-root-asset-inert",
      packages: tails.length,
      newPackages,
      hasModGameData,
      reason: `only new package is the mod root ${newPackages.join(", ")}, and there is no ModGameData tree for it to register`,
    };
  }
  return {
    mod,
    verdict: "can-skip-now",
    packages: tails.length,
    newPackages,
    hasModGameData,
    reason: tails.length ? "every package overrides a vanilla one" : "ships no packages at all",
  };
}

const labels: Record<Verdict, string> = {
  "can-skip-now": "can already skip NewContent (overrideOnly fires today)",
  "could-skip-if-root-asset-inert":
    "could skip if the mod-root .uasset does not need the NewContent pass",
  "needs-both": "genuinely needs both passes",
};

const reports = allValidMods.sort().map(analyzeMod);

for (const verdict of Object.keys(labels) as Verdict[]) {
  const group = reports.filter((r) => r.verdict === verdict);
  logger.log(`\n${labels[verdict]}: ${group.length}/${reports.length}`);
  for (const r of group) {
    // The uninteresting majority - cfg-only mods - would otherwise drown the two other groups.
    if (verdict === "can-skip-now" && !r.packages) continue;
    logger.log(`  ${r.mod} (${r.packages} package(s)) - ${r.reason}`);
  }
  if (verdict === "can-skip-now") {
    logger.log(`  ...plus ${group.filter((r) => !r.packages).length} mod(s) shipping no packages.`);
  }
}

const potential = reports.filter((r) => r.verdict !== "needs-both").length;
logger.log(
  `\nCooks that could run OverrideContent only: ${potential}/${reports.length} ` +
    `(${reports.filter((r) => r.verdict === "can-skip-now").length} under today's rule).`,
);
