import path from "node:path";
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";

import { logger } from "./logger.mts";
import { hasBaseGamePackage } from "./asset-registry.mts";
import { primarySdkModTarget, type SdkModTarget } from "./mod-meta-paths.mts";

/** Only Unreal packages are classified. .cfg patches are loose staged files, never listed. */
const packageExtensions = new Set([".uasset", ".umap"]);

const autogenerated = /^Autogenerated_\d+_([A-Za-z]+)$/;
/**
 * These patch and delete base-game world actors; no `/Game/` package of that name exists to
 * detect them by, so the registry test would wrongly call them new content.
 */
const autogeneratedOverride = new Set(["ActorPatchesData", "ActorDeletionsData"]);
/**
 * The Mod Editor leaves these out of both files. That is not "don't ship it": the lists reach
 * the cook as `-AssetsToNeverCookWithDLCList`, so a package in neither list is excluded by
 * neither pass and gets cooked into both containers.
 */
const autogeneratedExcluded = new Set([
  "WorldSubsystemData",
  "LocalizationDatabase",
  "ActorReplacementData",
]);

function walk(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((entry) => {
    const full = path.join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

/**
 * The lists GSCCookMod steers its two halves with. ModPackageClassifier normally writes them
 * when the mod is packaged from the Mod Editor; driving the cook from the CLI skips that, and
 * the cook then dies with `LogGSCAssetManager: Error: AssetsToNeverCookWithDLCList file not found`.
 *
 * A package at `Content/<tail>.uasset` is addressed as `/<mod>/<tail>`, and is Override Content
 * when the base game has `/Game/<tail>` (it is remapped onto Stalker2/Content at mount time) -
 * New Content otherwise, including the plugin's own `<mod>.uasset` root and anything under
 * ExternalActors/ContentBundle.
 */
export type ClassifiedPackages = {
  newPackages: string[];
  overridePackages: string[];
  /** In neither file, and so cooked by both passes. */
  unlisted: string[];
};

/** `target` picks which SDK mod to classify; omitted, it is the mod's only (or assets) one. */
export async function writePackageClassifierLists(
  target?: SdkModTarget,
): Promise<ClassifiedPackages> {
  const {
    name,
    modFolder,
    packageClassifierFolder: outDir,
  } = target ?? (await primarySdkModTarget);
  const contentDir = path.join(modFolder, "Content");

  // Path below Content with the extension dropped: the tail shared by the mod's package name
  // (/<mod>/<tail>) and the vanilla one it would override (/Game/<tail>).
  const tails = walk(contentDir)
    .filter((f) => packageExtensions.has(path.extname(f).toLowerCase()))
    .map((f) =>
      path
        .relative(contentDir, f)
        .replaceAll(path.sep, "/")
        .replace(/\.[^.]+$/, ""),
    )
    .sort();

  const vanilla = tails.length ? hasBaseGamePackage(tails[0]) !== null : true;
  if (!vanilla) {
    logger.warn(
      "Could not read the reference asset registry - treating every package as new content. " +
        "Check the lists before trusting the cook.",
    );
  }

  const newPackages: string[] = [];
  const overridePackages: string[] = [];
  const unlisted: string[] = [];
  for (const tail of tails) {
    const kind = autogenerated.exec(tail)?.[1];
    if (kind && autogeneratedExcluded.has(kind)) unlisted.push(`/${name}/${tail}`);
    else if (kind && autogeneratedOverride.has(kind)) overridePackages.push(`/${name}/${tail}`);
    // An unknown Autogenerated_* kind falls through to the registry test rather than guessing.
    else if (hasBaseGamePackage(tail)) overridePackages.push(`/${name}/${tail}`);
    else newPackages.push(`/${name}/${tail}`);
  }

  // No BOM, CRLF-terminated including the last line, empty file when empty - byte for byte
  // what the Mod Editor writes.
  const serialize = (lines: string[]) => lines.map((p) => p + "\r\n").join("");

  mkdirSync(outDir, { recursive: true });
  writeFileSync(path.join(outDir, "NewPackages.txt"), serialize(newPackages));
  writeFileSync(path.join(outDir, "OverridePackages.txt"), serialize(overridePackages));

  logger.log(
    `Wrote PackageClassifier lists to ${outDir}: ${newPackages.length} new, ` +
      `${overridePackages.length} override, ${unlisted.length} unlisted package(s).`,
  );
  newPackages.forEach((p) => logger.debug(`  new:      ${p}`));
  overridePackages.forEach((p) => logger.debug(`  override: ${p}`));
  unlisted.forEach((p) => logger.debug(`  unlisted: ${p}`));

  return { newPackages, overridePackages, unlisted };
}
