import path from "node:path";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { logger } from "./logger.mts";

/**
 * The gate that makes `trim-gamedata.mts` trustworthy: cook a mod normally, cook it again with
 * the GameData subtree hidden, and byte-compare the two trees. Identical output proves the
 * shortcut changed nothing for that class of mod.
 *
 *   node ./src/verify-cook-output.mts <treeA> <treeB> [--strict]
 *
 * Exit 0 when every file matches (tolerated differences allowed), 1 when anything real differs,
 * 2 on bad usage.
 *
 * Not everything a cook writes is reproducible. Verified against the four cooks sitting in
 * $SDK_PATH/Stalker2/SavedMods:
 *
 *  - `__ModKitWwiseCookAnchor_<mod>_<unixtime>__.uasset/.uexp`. The number is the cook's start
 *    time: FasterLootAnimation2x's two passes, same mod and same raw/, produced
 *    ..._1787675641__ and ..._1787677144__ - 25 minutes apart, exactly the gap between the
 *    OverrideContent and NewContent passes. So it changes on every run by construction.
 *  - `Manifest_UFSFiles_Win64.txt`. Every line carries an ISO mtime
 *    (`...ItemPrototypes_patch_NPCAttachments.cfg<TAB>2026-08-25T14:25:52.653Z`).
 *  - `Autogenerated_<unixtime>_<Kind>` packages, the same timestamp naming that
 *    package-classifier.mts already has to match with a regex. None of the four cooks on disk
 *    ship one (they are produced by world-actor-patching mods), but the name is time-derived.
 *
 * Those are DOCUMENTED EXCLUSIONS, listed in the report as `tolerated`, never silently dropped.
 * A second group - Metadata/, the ChunkManifest lists and the .pak/.ucas/.utoc containers -
 * differs only because it embeds the unstable names above; those are reported as tolerated too,
 * with the reason, and `--strict` makes every tolerated difference fail as well. Tolerances
 * excuse unstable bytes only - a file present in one tree and not the other always fails.
 */

/** A cook-start unix timestamp baked into a file name. Normalized away for path pairing. */
const timestampInName = /_(\d{9,11})_/g;

type Tolerance = { pattern: RegExp; why: string };

/** Time-derived by construction - the bytes cannot match between two runs. */
const unstableFiles: Tolerance[] = [
  {
    pattern: /__ModKitWwiseCookAnchor_[^/]*__\.(uasset|uexp)$/i,
    why: "name+bytes embed the cook start time",
  },
  { pattern: /(^|\/)Manifest_UFSFiles_Win64\.txt$/i, why: "lists a mtime per file" },
  {
    pattern: /(^|\/)Autogenerated_\d+_[A-Za-z]+\.(uasset|umap|uexp)$/i,
    why: "name embeds the cook start time",
  },
];

/** Stable in principle, but they contain one of the names above verbatim. */
const derivedFiles: Tolerance[] = [
  { pattern: /(^|\/)Metadata\//i, why: "references the Wwise anchor package" },
  { pattern: /(^|\/)ChunkManifest\/.*\.txt$/i, why: "lists the Wwise anchor package" },
  { pattern: /\.(pak|ucas|utoc)$/i, why: "container embeds the Wwise anchor package and offsets" },
];

function matchTolerance(relative: string, list: Tolerance[]): string | null {
  const posix = relative.replaceAll(path.sep, "/");
  return list.find((t) => t.pattern.test(posix))?.why ?? null;
}

function walk(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((entry) => {
    const full = path.join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

/**
 * Key a file by its path with any cook timestamp in it replaced, so the two runs' differently
 * named anchor packages pair up as one row instead of showing as only-in-A plus only-in-B.
 */
const normalizeKey = (relative: string) =>
  relative.replaceAll(path.sep, "/").replace(timestampInName, "_<TS>_");

export type Verdict = "same" | "differs" | "tolerated" | "only-in-a" | "only-in-b";
export type Row = { key: string; verdict: Verdict; detail: string };
export type Report = { rows: Row[]; counts: Record<Verdict, number>; ok: boolean };

export function compareTrees(a: string, b: string, { strict = false } = {}): Report {
  const index = (root: string) =>
    new Map(walk(root).map((f) => [normalizeKey(path.relative(root, f)), f]));
  const left = index(a);
  const right = index(b);

  const rows: Row[] = [];
  for (const key of [...new Set([...left.keys(), ...right.keys()])].sort()) {
    const fileA = left.get(key);
    const fileB = right.get(key);

    const tolerated = matchTolerance(key, unstableFiles) ?? matchTolerance(key, derivedFiles);

    // A file present on one side only is always a real failure, even for a tolerated path: the
    // tolerances excuse unstable *bytes*, never a missing or extra file. The anchor package's
    // renaming is already handled by normalizeKey, so it pairs up rather than showing here.
    if (!fileA || !fileB) {
      rows.push({
        key,
        verdict: fileA ? "only-in-a" : "only-in-b",
        detail: tolerated
          ? `tolerated path, but present on one side only (${tolerated})`
          : "missing",
      });
      continue;
    }

    const bytesA = readFileSync(fileA);
    const bytesB = readFileSync(fileB);
    if (bytesA.equals(bytesB)) {
      rows.push({ key, verdict: "same", detail: `${bytesA.length} B` });
      continue;
    }

    const detail = `${bytesA.length} B vs ${bytesB.length} B`;
    if (tolerated && !strict) {
      rows.push({ key, verdict: "tolerated", detail: `${detail} - ${tolerated}` });
    } else {
      rows.push({ key, verdict: "differs", detail });
    }
  }

  const counts = { same: 0, differs: 0, tolerated: 0, "only-in-a": 0, "only-in-b": 0 } as Record<
    Verdict,
    number
  >;
  rows.forEach((row) => (counts[row.verdict] += 1));

  return {
    rows,
    counts,
    ok: counts.differs === 0 && counts["only-in-a"] === 0 && counts["only-in-b"] === 0,
  };
}

const glyph: Record<Verdict, string> = {
  same: "  =  ",
  differs: "  X  ",
  tolerated: "  ~  ",
  "only-in-a": " A>  ",
  "only-in-b": "  <B ",
};

export function printReport(report: Report, { quiet = false } = {}) {
  for (const row of report.rows) {
    if (quiet && row.verdict === "same") continue;
    const line = `${glyph[row.verdict]} ${row.key}  (${row.detail})`;
    if (row.verdict === "differs" || row.verdict.startsWith("only")) logger.warn(line);
    else logger.log(line);
  }
  const { same, differs, tolerated } = report.counts;
  logger.log(
    `\n${same} same, ${differs} differ, ${tolerated} tolerated, ` +
      `${report.counts["only-in-a"]} only in A, ${report.counts["only-in-b"]} only in B`,
  );
  logger.log(
    report.ok
      ? "OK - the trimmed cook is byte-identical."
      : "MISMATCH - do not trust the trimmed cook.",
  );
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const strict = args.includes("--strict");
  const quiet = args.includes("--quiet");
  const [a, b] = args.filter((arg) => !arg.startsWith("--"));
  if (!a || !b) {
    logger.error("Usage: node ./src/verify-cook-output.mts <treeA> <treeB> [--strict] [--quiet]");
    process.exit(2);
  }
  for (const dir of [a, b]) {
    if (!existsSync(dir)) {
      logger.error(`No such tree: ${dir}`);
      process.exit(2);
    }
  }
  logger.log(`A = ${a}\nB = ${b}${strict ? "\n(strict: tolerated differences fail too)" : ""}\n`);
  const report = compareTrees(a, b, { strict });
  printReport(report, { quiet });
  process.exit(report.ok ? 0 : 1);
}
